sonar.projectKey=Andrimirana_Blowfish
sonar.organization=andrimirana

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=Blowfish
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=src
sonar.java.binaries=bin
sonar.java.source=12

# Language
# sonar.language=java now no need Sinar detect language autimatically 18/03/26

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8
